#!/usr/bin/env python3
"""Tests for .claude/hooks/pr-body.py — the deterministic PR body pipeline.

    python3 .claude/hooks/tests/test_pr_body.py

Standard library only, so it runs anywhere python3 does and needs no install.
"""
import importlib.util
import io
import json
import os
import sys
import unittest
from contextlib import redirect_stdout

HOOKS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
spec = importlib.util.spec_from_file_location("pr_body", os.path.join(HOOKS, "pr-body.py"))
pb = importlib.util.module_from_spec(spec)
spec.loader.exec_module(pb)

TICKET_URL = "https://trello.com/c/abc/123-a-card"
# what Bitbucket's editor writes, and what renders as a smart card rather than a blue link
TICKET = "[%s](%s){: data-inline-card='' }" % (TICKET_URL, TICKET_URL)

# The rendered contract. The two trailing spaces after **What** / **Why** are a Markdown
# hard break, and the blank line before `1.` is what makes Bitbucket render a real list.
VALID = (
    "Ticket: " + TICKET + "\n"
    "\n"
    "**What**  \n"
    "Added permission checks to number series.\n"
    "\n"
    "**Why**  \n"
    "Users without the required permission could modify the number series.\n"
    "\n"
    "**Check**\n"
    "\n"
    "1. User without permission cannot view the values.\n"
    "2. User with view permission can view but cannot edit.\n"
    "3. User with edit permission can save changes.\n"
)


def fmt(text, **kw):
    return pb.format_body(text, **kw)[0]


def problems(text):
    return pb.validate(text)


def run_hook(payload):
    buf = io.StringIO()
    stdin, sys.stdin = sys.stdin, io.StringIO(json.dumps(payload))
    try:
        with redirect_stdout(buf):
            pb.hook()
    finally:
        sys.stdin = stdin
    out = buf.getvalue().strip()
    return json.loads(out) if out else None


class Validator(unittest.TestCase):
    def test_valid_body_passes(self):
        self.assertEqual(problems(VALID), [])

    def test_empty_body_fails(self):
        self.assertEqual(problems(""), ["the body is empty"])
        self.assertEqual(problems("   \n\n"), ["the body is empty"])

    def test_missing_why_fails(self):
        body = VALID.replace("**Why**  \nUsers without the required permission could "
                             "modify the number series.\n\n", "")
        self.assertIn("missing Why section", problems(body))

    def test_missing_check_fails(self):
        body = VALID.split("**Check**")[0].rstrip() + "\n"
        self.assertIn("missing Check section", problems(body))

    def test_empty_what_fails(self):
        body = VALID.replace("Added permission checks to number series.\n", "")
        self.assertIn("What section is empty", problems(body))

    def test_empty_ticket_fails(self):
        body = VALID.replace("Ticket: " + TICKET, "Ticket:")
        self.assertIn("Ticket line is empty", problems(body))

    def test_missing_ticket_fails(self):
        body = VALID.split("\n", 2)[2]
        self.assertIn("missing Ticket section", problems(body))

    def test_check_without_numbers_fails(self):
        body = VALID.replace("1. User without permission cannot view the values.",
                             "- User without permission cannot view the values.")
        self.assertTrue(any("numbered" in p for p in problems(body)), problems(body))

    def test_check_numbering_must_be_sequential(self):
        body = VALID.replace("2. User with view", "3. User with view")
        self.assertIn("Check steps must be numbered 1..n in order", problems(body))

    def test_out_of_order_sections_fail(self):
        body = ("Ticket: FKC-1\n\n**Why**  \nBecause.\n\n**What**  \nA change.\n\n"
                "**Check**\n\n1. Look at it.\n")
        self.assertTrue(any("out of order" in p for p in problems(body)), problems(body))

    def test_attribution_in_final_body_fails(self):
        body = VALID + "\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n"
        self.assertTrue(any("attribution" in p for p in problems(body)), problems(body))
        self.assertTrue(any("attribution" in p for p in
                            problems(VALID + "\nGenerated by Claude Code\n")))
        self.assertTrue(any("attribution" in p for p in
                            problems(VALID + "\nCo-Authored-By: Claude <noreply@anthropic.com>\n")))

    def test_extra_sections_rejected(self):
        for extra in ("## Summary\nA summary.", "## Changes\nThings.",
                      "## Testing\nRan tests.", "## Notes\nNote."):
            body = VALID + "\n" + extra + "\n"
            self.assertTrue(any("unexpected section" in p for p in problems(body)),
                            "%s was accepted" % extra)

    def test_over_hard_word_budget_fails(self):
        body = VALID.replace("Added permission checks to number series.",
                             "word " * 300)
        self.assertTrue(any("over the 250 limit" in p for p in problems(body)), problems(body))

    def test_warnings_do_not_fail(self):
        body = VALID.replace("Added permission checks to number series.",
                             ("word " * 130).strip())
        self.assertEqual(problems(body), [])
        self.assertTrue(pb.warnings(body))


class Formatter(unittest.TestCase):
    def test_produces_the_required_shape(self):
        out = fmt("""Ticket: %s
What: Added permission checks.
Why: Prevent unauthorised changes.
Check:
1. Verify permissions.
""" % TICKET_URL)
        self.assertEqual(out, "Ticket: " + TICKET + "\n\n"
                              "**What**  \nAdded permission checks.\n\n"
                              "**Why**  \nPrevent unauthorised changes.\n\n"
                              "**Check**\n\n1. Verify permissions.\n")
        self.assertEqual(problems(out), [])

    def test_removes_claude_attribution(self):
        out = fmt("""Ticket: %s

What
Added permission checks.

Why
Prevent unauthorised changes.

Check:
1. Verify permissions.

---
🤖 Generated with [Claude Code](https://claude.com/claude-code)
Co-Authored-By: Claude <noreply@anthropic.com>
""" % TICKET_URL)
        self.assertNotIn("Claude", out)
        self.assertEqual(out, "Ticket: " + TICKET + "\n\n"
                              "**What**  \nAdded permission checks.\n\n"
                              "**Why**  \nPrevent unauthorised changes.\n\n"
                              "**Check**\n\n1. Verify permissions.\n")
        self.assertEqual(problems(out), [])

    def test_drops_banned_sections_and_reports_them(self):
        out, notes = pb.format_body("""Ticket: FKC-279

## Summary
This PR introduces a comprehensive permission check.

## What
Number series are gated by the No. Series permission.

## Why
Any admin could change them.

## Implementation Details
We added a shield rule.

## Check
1. Sign in without the permission.

## Testing
Unit tests pass.
""")
        self.assertNotIn("comprehensive", out)
        self.assertNotIn("shield rule", out)
        self.assertNotIn("Unit tests", out)
        self.assertIn("Number series are gated", out)
        self.assertEqual(sorted(n for n in notes if n.startswith("dropped")),
                         ["dropped section: implementation details",
                          "dropped section: summary", "dropped section: testing"])
        self.assertEqual(problems(out), [])

    def test_strips_markdown_headings_and_bold(self):
        out = fmt("""**Ticket:** FKC-279

**What** — Number series settings are hidden without the permission.

**Why** — Any admin could change them.

**Check**
1. Sign in without it.
""")
        self.assertEqual(out, "Ticket: FKC-279\n\n"
                              "**What**  \nNumber series settings are hidden without "
                              "the permission.\n\n"
                              "**Why**  \nAny admin could change them.\n\n"
                              "**Check**\n\n1. Sign in without it.\n")

    def test_preserves_meaning_verbatim(self):
        sentence = ("The purchase order and plant order number series are only given to, "
                    "and only accepted from, users whose role holds the new No. Series "
                    "view or edit permission.")
        out = fmt("Ticket: FKC-279\nWhat:\n%s\nWhy: Anyone signed in could rename orders.\n"
                  "Check:\n1. Try it.\n" % sentence)
        self.assertIn(sentence, out)

    def test_rewraps_but_does_not_reword(self):
        out = fmt("Ticket: FKC-279\n\nWhat\nThe purchase order and plant order\n"
                  "number series are gated.\n\nWhy\nAnyone could rename them.\n\n"
                  "Check:\n1. Try it.\n")
        self.assertIn("**What**  \nThe purchase order and plant order number series "
                      "are gated.", out)

    def test_bullets_become_numbers_and_renumber(self):
        out = fmt("Ticket: FKC-279\nWhat: A change.\nWhy: A reason.\n"
                  "Check:\n- first\n- second\n- third\n")
        self.assertIn("**Check**\n\n1. first\n2. second\n3. third\n", out)
        out = fmt("Ticket: FKC-279\nWhat: A change.\nWhy: A reason.\n"
                  "Check:\n3. first\n7. second\n")
        self.assertIn("**Check**\n\n1. first\n2. second\n", out)

    def test_bitbucket_escaped_numbering(self):
        """PR #124's real body: `**Check**` + markdown-escaped `1\\.` numbering."""
        out = fmt("Ticket: [FKC-279 | Trello](https://trello.com/c/bZZ0akWV/279)\n\n"
                  "**What**  \nThe number series are gated.\n\n"
                  "**Why**  \nAnyone could rename every future order.\n\n"
                  "**Check**   \n"
                  "1\\. With neither permission, a save is refused.   \n"
                  "2\\. Grant view: values show, saving is still refused.   \n")
        self.assertIn("**Check**\n\n1. With neither permission, a save is refused.\n"
                      "2. Grant view: values show, saving is still refused.\n", out)
        self.assertNotIn("1\\.", out)
        self.assertEqual(problems(out), [])

    def test_multi_paragraph_section_is_kept(self):
        out = fmt("Ticket: FKC-279\n\nWhat\nA change.\n\nWhy\nA reason.\n\n"
                  "It also grants the permission to the Administrator role.\n\n"
                  "Check:\n1. Try it.\n")
        self.assertIn("Administrator role", out)
        self.assertEqual(problems(out), [])

    def test_reorders_sections(self):
        out = fmt("Why: A reason.\nTicket: FKC-279\nCheck:\n1. Try it.\nWhat: A change.\n")
        self.assertEqual(out.split("\n")[0], "Ticket: FKC-279")
        self.assertEqual(problems(out), [])

    def test_accepts_section_aliases(self):
        out = fmt("Jira: FKC-279\nWhat: A change.\nWhy: A reason.\n"
                  "Verification:\n1. Try it.\n")
        self.assertEqual(problems(out), [])

    def test_normalises_spacing(self):
        out = fmt("Ticket: FKC-279   \n\n\n\nWhat:   A change.   \n\n\n"
                  "Why: A reason.\n\nCheck:\n1.   Try it.   \n\n\n")
        # the only trailing whitespace allowed is the deliberate hard break
        trailing = [l for l in out.split("\n") if l != l.rstrip()]
        self.assertEqual(trailing, ["**What**  ", "**Why**  "])
        self.assertNotIn("\n\n\n", out)
        self.assertTrue(out.endswith("1. Try it.\n"))

    def test_idempotent(self):
        once = fmt(VALID)
        self.assertEqual(once, VALID)
        self.assertEqual(fmt(once), once)

    def test_missing_why_raises(self):
        with self.assertRaises(pb.Invalid) as cm:
            fmt("Ticket: FKC-279\nWhat: A change.\nCheck:\n1. Try it.\n")
        self.assertIn("missing Why section", cm.exception.problems)

    def test_missing_check_raises(self):
        with self.assertRaises(pb.Invalid) as cm:
            fmt("Ticket: FKC-279\nWhat: A change.\nWhy: A reason.\n")
        self.assertIn("missing Check section", cm.exception.problems)

    def test_empty_what_raises(self):
        with self.assertRaises(pb.Invalid) as cm:
            fmt("Ticket: FKC-279\nWhat:\nWhy: A reason.\nCheck:\n1. Try it.\n")
        self.assertIn("What section is empty", cm.exception.problems)

    def test_missing_ticket_raises_and_never_invents_one(self):
        with self.assertRaises(pb.Invalid) as cm:
            fmt("What: A change.\nWhy: A reason.\nCheck:\n1. Try it.\n")
        self.assertTrue(any("missing Ticket line" in p for p in cm.exception.problems))

    def test_ticket_none_is_allowed_for_a_change_with_no_ticket(self):
        out = fmt("Ticket: none\nWhat: A change.\nWhy: A reason.\nCheck:\n1. Try it.\n")
        self.assertTrue(out.startswith("Ticket: none"))
        self.assertEqual(problems(out), [])

    def test_ticket_key_expands_only_with_a_base_url(self):
        self.assertTrue(fmt("Ticket: FKC-279\nWhat: A.\nWhy: B.\nCheck:\n1. C.\n")
                        .startswith("Ticket: FKC-279"))
        url = "https://x.atlassian.net/browse/FKC-279"
        self.assertTrue(fmt("Ticket: FKC-279\nWhat: A.\nWhy: B.\nCheck:\n1. C.\n",
                            base_url="https://x.atlassian.net/")
                        .startswith("Ticket: [%s](%s){: data-inline-card='' }" % (url, url)))

    def test_unknown_heading_is_rejected_not_guessed(self):
        with self.assertRaises(pb.Invalid) as cm:
            fmt("Ticket: FKC-279\nWhat: A change.\nWhy: A reason.\n"
                "## Deployment plan\nRun the migration.\nCheck:\n1. Try it.\n")
        self.assertTrue(any("unexpected section: Deployment plan" in p
                            for p in cm.exception.problems), cm.exception.problems)


class Rendering(unittest.TestCase):
    """The bug from PR #125: valid-looking plain text renders as one wall of paragraphs."""

    PLAIN = ("Ticket: https://trello.com/c/SeMnPwgb/281\n\nWhat\nA change.\n\n"
             "Why\nA reason.\n\nCheck:\n1. Try it.\n2. Try it again.\n")

    def test_plain_labels_are_rejected(self):
        self.assertTrue(any("canonical Markdown shape" in p for p in problems(self.PLAIN)),
                        problems(self.PLAIN))

    def test_plain_labels_are_repaired_by_the_formatter(self):
        out = fmt(self.PLAIN)
        self.assertEqual(problems(out), [])
        self.assertIn("**What**  \nA change.", out)

    def test_labels_are_bold_with_a_hard_break(self):
        out = fmt(self.PLAIN)
        self.assertIn("**What**  \n", out)
        self.assertIn("**Why**  \n", out)

    def test_numbered_list_has_a_blank_line_above_it(self):
        lines = fmt(self.PLAIN).split("\n")
        i = lines.index("**Check**")
        self.assertEqual(lines[i + 1], "")
        self.assertEqual(lines[i + 2], "1. Try it.")

    def test_check_label_carries_no_hard_break(self):
        # a hard break before a list would put the list inside the label's paragraph
        self.assertIn("\n**Check**\n\n", fmt(self.PLAIN))
        self.assertNotIn("**Check**  ", fmt(self.PLAIN))

    def test_a_ticket_url_becomes_a_bitbucket_smart_card(self):
        for given in (TICKET_URL,
                      "[%s](%s)" % (TICKET_URL, TICKET_URL),
                      "[A card title](%s)" % TICKET_URL,   # title comes from the card itself
                      TICKET):
            out = fmt("Ticket: %s\nWhat: A change.\nWhy: A reason.\nCheck:\n1. Try it.\n"
                      % given)
            self.assertTrue(out.startswith("Ticket: " + TICKET + "\n"),
                            "%r -> %r" % (given, out.split("\n")[0]))
            self.assertEqual(problems(out), [])

    def test_a_bare_key_is_left_alone(self):
        out = fmt("Ticket: FKC-281\nWhat: A change.\nWhy: A reason.\nCheck:\n1. Try it.\n")
        self.assertTrue(out.startswith("Ticket: FKC-281\n"))
        out = fmt("Ticket: none\nWhat: A change.\nWhy: A reason.\nCheck:\n1. Try it.\n")
        self.assertTrue(out.startswith("Ticket: none\n"))

    def test_reproduces_the_hand_fixed_pr_125_body(self):
        """The body a human repaired in the Bitbucket editor is what the formatter emits."""
        url = "https://trello.com/c/SeMnPwgb/281-no-series-subcontract-series-backend"
        hand_fixed = (
            "Ticket: [%s](%s){: data-inline-card='' } \n\n"
            "**What**  \nOne system-wide subcontract order number series is now held.\n\n"
            "**Why**  \nNothing held a subcontract prefix or suffix.\n\n"
            "**Check**\n\n"
            "1. Apply the migration twice on a scratch schema, then roll back. \n"
            "2. Save a blank suffix: refused, previous kept.\n\n\u200c" % (url, url))
        expected = (
            "Ticket: [%s](%s){: data-inline-card='' }\n\n"
            "**What**  \nOne system-wide subcontract order number series is now held.\n\n"
            "**Why**  \nNothing held a subcontract prefix or suffix.\n\n"
            "**Check**\n\n"
            "1. Apply the migration twice on a scratch schema, then roll back.\n"
            "2. Save a blank suffix: refused, previous kept.\n" % (url, url))
        self.assertEqual(fmt(hand_fixed), expected)
        self.assertEqual(problems(expected), [])


class Hook(unittest.TestCase):
    PATH = "/repositories/lisafk/fk-admin-panel-be/pullrequests"

    def payload(self, description, path=None, tool="mcp__bitbucket__bb_post", body=None):
        b = {"title": "A change", "source": {"branch": {"name": "feat/x"}}}
        if description is not None:
            b["description"] = description
        if body:
            b.update(body)
        return {"tool_name": tool, "tool_input": {"path": path or self.PATH, "body": b}}

    def test_valid_body_is_allowed_silently(self):
        self.assertIsNone(run_hook(self.payload(VALID)))

    def test_attribution_is_stripped_in_flight(self):
        out = run_hook(self.payload(
            VALID + "\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n"))
        fixed = out["hookSpecificOutput"]["updatedInput"]["body"]["description"]
        self.assertEqual(fixed, VALID)
        self.assertNotIn("permissionDecision", out["hookSpecificOutput"])

    def test_headings_are_normalised_in_flight(self):
        out = run_hook(self.payload("## Ticket\nFKC-279\n\n## What\nA change.\n\n"
                                    "## Why\nA reason.\n\n## Check\n- Try it.\n"))
        fixed = out["hookSpecificOutput"]["updatedInput"]["body"]["description"]
        self.assertEqual(fixed, "Ticket: FKC-279\n\n**What**  \nA change.\n\n"
                                "**Why**  \nA reason.\n\n**Check**\n\n1. Try it.\n")

    def test_missing_why_is_denied(self):
        out = run_hook(self.payload("Ticket: FKC-279\n\n**What**  \nA change.\n\n"
                                    "**Check**\n\n1. Try it.\n"))
        hso = out["hookSpecificOutput"]
        self.assertEqual(hso["permissionDecision"], "deny")
        self.assertIn("missing Why section", hso["permissionDecisionReason"])
        self.assertIn("The PR was not created.", hso["permissionDecisionReason"])

    def test_empty_description_is_denied(self):
        out = run_hook(self.payload(""))
        self.assertEqual(out["hookSpecificOutput"]["permissionDecision"], "deny")
        out = run_hook(self.payload(None))
        self.assertEqual(out["hookSpecificOutput"]["permissionDecision"], "deny")

    def test_pr_update_is_covered(self):
        out = run_hook(self.payload("Ticket: FKC-279\n\n**What**  \nA change.\n\n"
                                    "**Check**\n\n1. Try it.\n",
                                    path=self.PATH + "/124", tool="mcp__bitbucket__bb_put"))
        self.assertEqual(out["hookSpecificOutput"]["permissionDecision"], "deny")

    def test_other_bitbucket_calls_are_untouched(self):
        self.assertIsNone(run_hook(self.payload("hi", path=self.PATH + "/124/comments")))
        self.assertIsNone(run_hook(self.payload("hi", path=self.PATH + "/124/approve")))
        self.assertIsNone(run_hook(self.payload("hi", path="/repositories/lisafk/fk-mobile")))
        self.assertIsNone(run_hook({"tool_name": "Bash", "tool_input": {"command": "ls"}}))

    def test_pr_write_without_title_or_description_is_untouched(self):
        self.assertIsNone(run_hook({"tool_name": "mcp__bitbucket__bb_put",
                                    "tool_input": {"path": self.PATH + "/124",
                                                   "body": {"draft": False}}}))


if __name__ == "__main__":
    unittest.main(verbosity=2)
